version: "3.8"

services:
  db:
    image: postgres:17.4-alpine
    container_name: progresssoft-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - progresssoft-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: progresssoft-app
    restart: unless-stopped
    environment:
      spring.datasource.url: jdbc:postgresql://db:${POSTGRES_DB}
      spring.datasource.username: ${POSTGRES_USER}
      spring.datasource.password: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - progresssoft-network


volumes:
  db-data:
    name: progresssoft-db-data
    driver: local

networks:
  progresssoft-network:
    name: progresssoft-network
    driver: bridge
    attachable: true