spring:
  config:
    import: optional:file:.env[.properties]
    
  profiles:
    active: dev
    
  application:
    name: progresssoft

  datasource:
      url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.progresssoft: INFO
        
server:
  port: 8080