spring:
    
  profiles:
    active: dev
    
  application:
    name: progresssoft

  datasource:
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.progresssoft: INFO
        
server:
  port: 8080