spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.progresssoft: DEBUG
    org.hibernate.SQL: DEBUG